export const AuthConstant = {
    DEFAULTERR : "sorry unable to process! please try again later",
    LOGINSUCCESS : "LOGIN_SUCCESS",
    LOGINFAIL : "LOGIN_FAIL",

    REGISTERSUCCESS : "REGISTER_SUCCESS",
    REGISTERFAIL : "REGISTER_FAIL",

    VERIFYSUCCESS : "VERIFY_SUCCESS",
    VERIFYFAIL : "VERIFY_FAIL",

    UPDATEPASSWORDSUCCESS : "UPDATE_PASSWORD_SUCCESS",
    UPDATEPASSWORDFAIL : "UPDATE_PASSWORD_FAIL"

}
