export const UserConstant = {
  DEFAULTERR : "sorry unable to process! please try again later",

  GETUSERLISTSUCCESS : "GET_USER_LIST_SUCCESS",
  GETUSERLISTFAIL : "GET_USER_LIST_FAIL",

  GETUSERDETAILSUCCESS : "GET_USER_DETAIL_SUCCESS",
  GETUSERDETAILFAIL : "GET_USER_DETAIL_FAIL",

  SAVEUSERDETAILSUCCESS : "SAVE_USER_DETAIL_SUCCESS",
  SAVEUSERDETAILFAIL : "SAVE_USER_DETAIL_FAIL"
  
}
